name: Build and Publish

on: workflow_dispatch

jobs:
  build-and-publish:
  name: Build & Upload Package
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v3
    - name: build
      run: poetry build
    - name: publish
      run: poetry publish
