name: Build and Publish

on: workflow_dispatch
permissions:
  id-token: write
jobs:
  build-and-publish:
    name: Build & Upload Package
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
            version: "latest"
            activate-environment: true
            enable-cache: true
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"
      - name: Install Dependencies
        run: |
          uv sync --all-extras --all-groups
      - name: build
        run: uv build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@v1.13.0
        with:
          verbose: true
          print-hash: true
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v3.0.0
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
