name: Build and Publish

on: workflow_dispatch
permissions:
  id-token: write
jobs:
  build-and-publish:
    name: Build & Upload Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir "poetry==1.8.3"
      - name: build
        run: poetry build
      - name: Publish to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
          print-hash: true
      - name: Sign published artifacts
        uses: sigstore/gh-action-sigstore-python@v2.1.0
        with:
          inputs: ./dist/*.tar.gz ./dist/*.whl
          release-signing-artifacts: true
