name: Build and Publish

on: workflow_dispatch

jobs:
  build-and-publish:
    name: Build & Upload Package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir "poetry==1.7.1"
      - name: build
        run: poetry build
      - name: publish
        run: poetry publish
